name: ej1-workflow
on: 
  push:
    branches:
      - main
jobs:
  trab:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar el codigo
        uses: actions/checkout@v4
      - name: Configurar Node Version 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: NPM i
        run: npm i
      - name: NPM test
        run: npm test
      - name: Construir imagen
        uses: cloudposse/github-action-docker-compose-test-run@main
        with:
          file: docker-compose.yml
